#!/bin/bash
source /usr/local/gromacs/bin/GMXRC

for file in complex.pdb
do
  nuev=$(echo $file | sed 's/.pdb//g' ) 
   gmx pdb2gmx -ignh -nice 0 -f $file -p $nuev.top -o $nuev.gro -i $nuev.itp -n $nuev.ndx -ff charmm27-David  -water tip3p
#   gmx editconf -f $nuev.gro -o $nuev-01.gro -d 2 -c
#   gmx solvate -cp $nuev-01.gro -cs spc216.gro -o $nuev-01.gro -nice 0 -p $nuev.top 
#   gmx grompp -f ions.mdp -c $nuev-01.gro -p $nuev.top -o $nuev-02.tpr -po $nuev-01.mdp 
#   echo 13|  
#   gmx genion -s $nuev-02.tpr -o $nuev-02.gro -p $nuev.top -nice 0 -pname NA -nname CL -neutral
#   gmx grompp -f minim.mdp -c $nuev-02.gro -p $nuev.top -o $nuev-02.tpr -po $nuev-02.mdp
#   gmx mdrun -nice 0 -v -s -deffnm $nuev-02
#   gmx grompp -f nvt.mdp -c $nuev-02.gro -p $nuev.top -o $nuev-03.tpr -po $nuev-02.mdp -r $nuev-02.gro -maxwarn 1
#   gmx mdrun -nice 0 -v -s -deffnm $nuev-03 -gpu_id 0
#   gmx grompp -f npt.mdp -c $nuev-03.gro -p $nuev.top -o $nuev-04.tpr -po $nuev-03.mdp -r $nuev-03.gro -maxwarn 1
#   gmx mdrun -nice 0 -v -s -deffnm $nuev-04 -gpu_id 0
#   gmx grompp -f md.mdp -c $nuev-04.gro -p $nuev.top -o $nuev-05.tpr -po $nuev-04.mdp -r $nuev-04.gro -maxwarn 1
#   gmx mdrun -nice 0 -v -s -deffnm $nuev-05 -gpu_id 0   
  rm \#*
done  
